from schedule_combobox_appear_hide import *


def schedule_to_main_page(self,mode_state):
    Monday_hide(self)
    Tuesday_hide(self)
    Wednesday_hide(self)
    Thursday_hide(self)
    Friday_hide(self)
    Saturday_hide(self)
    Sunday_hide(self)
    self.pushButton_add.setVisible(False)
    self.pushButton_minus.setVisible(False)
    self.label_tem1.setVisible(False)
    self.label_tem2.setVisible(False)
    self.label_tem3.setVisible(False)
    self.label_tem4.setVisible(False)
    self.label_day.setVisible(False)
    self.label_time_range.setVisible(False)
    self.label_set1.setVisible(False)
    self.pushButton_up1.setVisible(False)
    self.pushButton_left1.setVisible(False)
    self.pushButton_right1.setVisible(False)
    self.pushButton_down1.setVisible(False)
    self.pushButton_1.setVisible(False)
    self.pushButton_2.setVisible(False)
    self.pushButton_5.setVisible(False)
    self.pushButton_4.setVisible(False)
    self.pushButton_3.setVisible(False)
    self.pushButton_6.setVisible(False)
    self.pushButton_7.setVisible(False)
    self.label_tem5.setVisible(False)
    self.label_tem6.setVisible(False)
    self.pushButton_back.setVisible(False)
    self.Title_schedule.setVisible(False)
    
    self.modebox.setVisible(True)
    self.label_modestate.setVisible(True)
    self.label_fanstate.setVisible(True)
    
    self.pushButton_right.setVisible(True)
    self.pushButton_onauto.setVisible(True)
    self.label_set.setVisible(True)
    self.pushButton_down.setVisible(True)
    self.pushButton_left.setVisible(True)
    self.label_current.setVisible(True)
    self.label_curtemp.setVisible(True)
    self.pushButton_setting.setVisible(True)
    self.pushButton_up.setVisible(True)
    self.label_hold.setVisible(True)
    self.label_mode_running.setVisible(True)
    if(mode_state!='off'):
        self.label_settemp.setVisible(True)
def setting_to_middle(self):
    self.modebox.setVisible(False)
    self.label_modestate.setVisible(False)
    self.label_fanstate.setVisible(False)
    self.label_settemp.setVisible(False)
    self.pushButton_right.setVisible(False)
    self.pushButton_onauto.setVisible(False)
    self.label_set.setVisible(False)
    self.pushButton_down.setVisible(False)
    self.pushButton_left.setVisible(False)
    self.label_current.setVisible(False)
    self.label_curtemp.setVisible(False)
    self.pushButton_setting.setVisible(False)
    self.pushButton_up.setVisible(False)    
    self.pushButton_back.setVisible(False)
    self.label_hold.setVisible(False)
    self.label_mode_running.setVisible(False)
    
    self.pushButton_back1.setVisible(True)
    self.pushButton_schedule.setVisible(True)
    self.pushButton_mode.setVisible(True)    
def middle_to_mainpage(self,mode_state):
    self.pushButton_back1.setVisible(False)
    self.pushButton_schedule.setVisible(False)
    self.pushButton_mode.setVisible(False)
    self.modebox.setVisible(True)
    self.label_modestate.setVisible(True)
    self.label_fanstate.setVisible(True)
    self.pushButton_right.setVisible(True)
    self.pushButton_onauto.setVisible(True)
    self.label_set.setVisible(True)
    self.pushButton_down.setVisible(True)
    self.pushButton_left.setVisible(True)
    self.label_current.setVisible(True)
    self.label_curtemp.setVisible(True)
    self.pushButton_setting.setVisible(True)
    self.pushButton_up.setVisible(True)
    self.label_hold.setVisible(True)
    self.label_mode_running.setVisible(True)
    if(mode_state!='off'):
        self.label_settemp.setVisible(True)

def middle_to_schedule(self):
    self.pushButton_back1.setVisible(False)
    self.pushButton_schedule.setVisible(False)
    self.pushButton_mode.setVisible(False)
    Monday_appear(self)
    self.pushButton_add.setVisible(True)
    self.pushButton_minus.setVisible(True)
    self.label_tem1.setVisible(True)
    self.label_tem2.setVisible(True)
    self.label_tem3.setVisible(True)
    self.label_tem4.setVisible(True)
    self.label_day.setVisible(True)
    self.label_time_range.setVisible(True)
    self.label_set1.setVisible(True)
    self.pushButton_up1.setVisible(True)
    self.pushButton_left1.setVisible(True)
    self.pushButton_right1.setVisible(True)
    self.pushButton_down1.setVisible(True)
    self.pushButton_1.setVisible(True)
    self.pushButton_2.setVisible(True)
    self.pushButton_5.setVisible(True)
    self.pushButton_4.setVisible(True)
    self.pushButton_3.setVisible(True)
    self.pushButton_6.setVisible(True)
    self.pushButton_7.setVisible(True)
    self.label_tem5.setVisible(True)
    self.label_tem6.setVisible(True)
    self.pushButton_back.setVisible(True)
    self.Title_schedule.setVisible(True)
    
def middle_to_mode(self):
    self.pushButton_back1.setVisible(False)
    self.pushButton_schedule.setVisible(False)
    self.pushButton_mode.setVisible(False)
    
    self.Title_mode.setVisible(True)
    self.label_mode_sleep.setVisible(True)
    self.label_mode_save.setVisible(True)
    self.label_mode_precool.setVisible(True)
    self.pushButton_back2.setVisible(True)
    self.pushButton_sleep.setVisible(True)
    self.pushButton_cool.setVisible(True)
    self.pushButton_save.setVisible(True)
    self.label_mode_time.setVisible(True)
    self.label_mode_set.setVisible(True)
    self.label_mode_settemp.setVisible(True)
    self.label_mode_toset.setVisible(True)
    self.label_sleep_lowertemp.setVisible(True)
    self.label_mode_preheat.setVisible(True)
    self.label_mode_pretemp.setVisible(True)
    self.pushButton_heat.setVisible(True)
    self.label_mode_fanauto.setVisible(True)
    self.label_leaving_lowertemp.setVisible(True)
    self.horizontalSlider_time1.setVisible(True)
    self.horizontalSlider_time2.setVisible(True)
    self.label_slider_1.setVisible(True)
    self.label_slider_2.setVisible(True)
    

def mode_to_main_page(self,mode_state):
    self.Title_mode.setVisible(False)
    self.label_mode_sleep.setVisible(False)
    self.label_mode_save.setVisible(False)
    self.label_mode_precool.setVisible(False)
    self.pushButton_back2.setVisible(False)
    self.pushButton_sleep.setVisible(False)
    self.pushButton_cool.setVisible(False)
    self.pushButton_save.setVisible(False)
    self.label_mode_time.setVisible(False)
    self.label_mode_set.setVisible(False)
    self.label_mode_settemp.setVisible(False)
    self.label_mode_toset.setVisible(False)
    self.label_sleep_lowertemp.setVisible(False)
    self.label_mode_preheat.setVisible(False)
    self.label_mode_pretemp.setVisible(False)
    self.pushButton_heat.setVisible(False)
    self.label_mode_fanauto.setVisible(False)
    self.label_leaving_lowertemp.setVisible(False)
    self.horizontalSlider_time1.setVisible(False)
    self.horizontalSlider_time2.setVisible(False)
    self.label_slider_1.setVisible(False)
    self.label_slider_2.setVisible(False)

    
    self.modebox.setVisible(True)
    self.label_modestate.setVisible(True)
    self.label_fanstate.setVisible(True)
    self.pushButton_right.setVisible(True)
    self.pushButton_onauto.setVisible(True)
    self.label_set.setVisible(True)
    self.pushButton_down.setVisible(True)
    self.pushButton_left.setVisible(True)
    self.label_current.setVisible(True)
    self.label_curtemp.setVisible(True)
    self.pushButton_setting.setVisible(True)
    self.pushButton_up.setVisible(True)
    self.label_hold.setVisible(True)
    self.label_mode_running.setVisible(True)
    if(mode_state!='off'):
        self.label_settemp.setVisible(True)

