from thermostat import *
sch_1=[]
sch_2=[]
sch_3=[]
sch_4=[]
sch_5=[]
sch_6=[]
sch_7=[]
def day_change(self,day_number):
    if(day_number==1):
        self.pushButton_1.setStyleSheet('color:red')
        self.pushButton_2.setStyleSheet('color:black')
        self.pushButton_3.setStyleSheet('color:black')
        self.pushButton_4.setStyleSheet('color:black')
        self.pushButton_5.setStyleSheet('color:black')
        self.pushButton_6.setStyleSheet('color:black')
        self.pushButton_7.setStyleSheet('color:black')
    elif(day_number==2):
        self.pushButton_1.setStyleSheet('color:black')
        self.pushButton_2.setStyleSheet('color:red')
        self.pushButton_3.setStyleSheet('color:black')
        self.pushButton_4.setStyleSheet('color:black')
        self.pushButton_5.setStyleSheet('color:black')
        self.pushButton_6.setStyleSheet('color:black')
        self.pushButton_7.setStyleSheet('color:black')
        
    elif(day_number==3):
        self.pushButton_1.setStyleSheet('color:black')
        self.pushButton_2.setStyleSheet('color:black')
        self.pushButton_3.setStyleSheet('color:red')
        self.pushButton_4.setStyleSheet('color:black')
        self.pushButton_5.setStyleSheet('color:black')
        self.pushButton_6.setStyleSheet('color:black')
        self.pushButton_7.setStyleSheet('color:black')
    elif(day_number==4):
        self.pushButton_1.setStyleSheet('color:black')
        self.pushButton_2.setStyleSheet('color:black')
        self.pushButton_3.setStyleSheet('color:black')
        self.pushButton_4.setStyleSheet('color:red')
        self.pushButton_5.setStyleSheet('color:black')
        self.pushButton_6.setStyleSheet('color:black')
        self.pushButton_7.setStyleSheet('color:black')
    elif(day_number==5):
        self.pushButton_1.setStyleSheet('color:black')
        self.pushButton_2.setStyleSheet('color:black')
        self.pushButton_3.setStyleSheet('color:black')
        self.pushButton_4.setStyleSheet('color:black')
        self.pushButton_5.setStyleSheet('color:red')
        self.pushButton_6.setStyleSheet('color:black')
        self.pushButton_7.setStyleSheet('color:black')
    elif(day_number==6):
        self.pushButton_1.setStyleSheet('color:black')
        self.pushButton_2.setStyleSheet('color:black')
        self.pushButton_3.setStyleSheet('color:black')
        self.pushButton_4.setStyleSheet('color:black')
        self.pushButton_5.setStyleSheet('color:black')
        self.pushButton_6.setStyleSheet('color:red')
        self.pushButton_7.setStyleSheet('color:black')
    else:
        self.pushButton_1.setStyleSheet('color:black')
        self.pushButton_2.setStyleSheet('color:black')
        self.pushButton_3.setStyleSheet('color:black')
        self.pushButton_4.setStyleSheet('color:black')
        self.pushButton_5.setStyleSheet('color:black')
        self.pushButton_6.setStyleSheet('color:black')
        self.pushButton_7.setStyleSheet('color:red')
def schedule_temp_position_change_right(self,day_number,tem_number, sch_number, tem_set_number):
    tem_number+=1;
    if(tem_number==1):
            tem_set_number=1
            self.label_tem1.setStyleSheet('color:red')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
    if(tem_number==2):
            tem_set_number=2
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:red')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
    if(tem_number==3):
            tem_set_number=3
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:red')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
    if(tem_number==4):
            tem_set_number=4
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:red')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
            if(sch_number==4):
                tem_set_number=4
                tem_number=0;
    if(tem_number==5):
            tem_set_number=5
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:red')
            self.label_tem6.setStyleSheet('color:black')
            if(sch_number==5):
                tem_set_number=5
                tem_number=0
    if(tem_number==6):
            tem_set_number=6
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:red')
    if(tem_number==7):
            tem_set_number=1
            tem_number=1;
            self.label_tem1.setStyleSheet('color:red')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
    #print(tem_number)
    return  tem_number, sch_number, tem_set_number
def schedule_temp_position_change_left(self,day_number,tem_number, sch_number, tem_set_number):
        tem_number-=1;
        if(tem_number<0):
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
            if(sch_number==4):
                tem_set_number=3
                tem_number=3;
                self.label_tem3.setStyleSheet('color:red')
            if(sch_number==5):
                tem_set_number=4
                tem_number=4;
                self.label_tem4.setStyleSheet('color:red')
        if(tem_number==1):
            self.label_tem1.setStyleSheet('color:red')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
            tem_set_number=1
        if(tem_number==2):
            tem_set_number=2
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:red')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
        if(tem_number==3):
            tem_set_number=3
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:red')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
        if(tem_number==4):
            tem_set_number=4
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:red')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:black')
            if(sch_number==4):
                tem_number=0;         
        if(tem_number==5):
            tem_set_number=5
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:red')
            self.label_tem6.setStyleSheet('color:black')
        if(tem_number==6):
            tem_set_number=6
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:red')
        if(tem_number==0):
            tem_set_number=6
            tem_number=6;
            self.label_tem1.setStyleSheet('color:black')
            self.label_tem2.setStyleSheet('color:black')
            self.label_tem3.setStyleSheet('color:black')
            self.label_tem4.setStyleSheet('color:black')
            self.label_tem5.setStyleSheet('color:black')
            self.label_tem6.setStyleSheet('color:red')
            if(sch_number==4):
                tem_set_number=4
                tem_number=0;
                self.label_tem4.setStyleSheet('color:red')
            if(sch_number==5):
                tem_set_number=5
                tem_number=0;
                self.label_tem5.setStyleSheet('color:red')
        
        #print(tem_number)
        return  tem_number, sch_number, tem_set_number

def save_sch_time(self):
        global sch_1,sch_2,sch_3,sch_4,sch_5,sch_6,sch_7
        sch_1=[]
        sch_1.append(self.comboBox_1_1.currentText())
        sch_1.append(self.comboBox_1_2.currentText())
        sch_1.append(self.comboBox_1_3.currentText())
        sch_1.append(self.comboBox_1_4.currentText())
        sch_1.append(self.comboBox_1_5.currentText())
        sch_1.append(self.comboBox_1_6.currentText())
        sch_1.append(self.comboBox_1_7.currentText())
        sch_1.append(self.comboBox_1_8.currentText())
        sch_1.append(self.comboBox_1_9.currentText())
        sch_1.append(self.comboBox_1_10.currentText())
        sch_1.append(self.comboBox_1_11.currentText())
        sch_1.append(self.comboBox_1_12.currentText())
    
        sch_2=[]
        sch_2.append(self.comboBox_2_1.currentText())
        sch_2.append(self.comboBox_2_2.currentText())
        sch_2.append(self.comboBox_2_3.currentText())
        sch_2.append(self.comboBox_2_4.currentText())
        sch_2.append(self.comboBox_2_5.currentText())
        sch_2.append(self.comboBox_2_6.currentText())
        sch_2.append(self.comboBox_2_7.currentText())
        sch_2.append(self.comboBox_2_8.currentText())
        sch_2.append(self.comboBox_2_9.currentText())
        sch_2.append(self.comboBox_2_10.currentText())
        sch_2.append(self.comboBox_2_11.currentText())
        sch_2.append(self.comboBox_2_12.currentText())
        
        sch_3=[]
        sch_3.append(self.comboBox_3_1.currentText())
        sch_3.append(self.comboBox_3_2.currentText())
        sch_3.append(self.comboBox_3_3.currentText())
        sch_3.append(self.comboBox_3_4.currentText())
        sch_3.append(self.comboBox_3_5.currentText())
        sch_3.append(self.comboBox_3_6.currentText())
        sch_3.append(self.comboBox_3_7.currentText())
        sch_3.append(self.comboBox_3_8.currentText())
        sch_3.append(self.comboBox_3_9.currentText())
        sch_3.append(self.comboBox_3_10.currentText())
        sch_3.append(self.comboBox_3_11.currentText())
        sch_3.append(self.comboBox_3_12.currentText())

        sch_4=[]
        sch_4.append(self.comboBox_4_1.currentText())
        sch_4.append(self.comboBox_4_2.currentText())
        sch_4.append(self.comboBox_4_3.currentText())
        sch_4.append(self.comboBox_4_4.currentText())
        sch_4.append(self.comboBox_4_5.currentText())
        sch_4.append(self.comboBox_4_6.currentText())
        sch_4.append(self.comboBox_4_7.currentText())
        sch_4.append(self.comboBox_4_8.currentText())
        sch_4.append(self.comboBox_4_9.currentText())
        sch_4.append(self.comboBox_4_10.currentText())
        sch_4.append(self.comboBox_4_11.currentText())
        sch_4.append(self.comboBox_4_12.currentText())        

        sch_5=[]
        sch_5.append(self.comboBox_5_1.currentText())
        sch_5.append(self.comboBox_5_2.currentText())
        sch_5.append(self.comboBox_5_3.currentText())
        sch_5.append(self.comboBox_5_4.currentText())
        sch_5.append(self.comboBox_5_5.currentText())
        sch_5.append(self.comboBox_5_6.currentText())
        sch_5.append(self.comboBox_5_7.currentText())
        sch_5.append(self.comboBox_5_8.currentText())
        sch_5.append(self.comboBox_5_9.currentText())
        sch_5.append(self.comboBox_5_10.currentText())
        sch_5.append(self.comboBox_5_11.currentText())
        sch_5.append(self.comboBox_5_12.currentText())

        sch_6=[]
        sch_6.append(self.comboBox_6_1.currentText())
        sch_6.append(self.comboBox_6_2.currentText())
        sch_6.append(self.comboBox_6_3.currentText())
        sch_6.append(self.comboBox_6_4.currentText())
        sch_6.append(self.comboBox_6_5.currentText())
        sch_6.append(self.comboBox_6_6.currentText())
        sch_6.append(self.comboBox_6_7.currentText())
        sch_6.append(self.comboBox_6_8.currentText())
        sch_6.append(self.comboBox_6_9.currentText())
        sch_6.append(self.comboBox_6_10.currentText())
        sch_6.append(self.comboBox_6_11.currentText())
        sch_6.append(self.comboBox_6_12.currentText())

        sch_7=[]
        sch_7.append(self.comboBox_7_1.currentText())
        sch_7.append(self.comboBox_7_2.currentText())
        sch_7.append(self.comboBox_7_3.currentText())
        sch_7.append(self.comboBox_7_4.currentText())
        sch_7.append(self.comboBox_7_5.currentText())
        sch_7.append(self.comboBox_7_6.currentText())
        sch_7.append(self.comboBox_7_7.currentText())
        sch_7.append(self.comboBox_7_8.currentText())
        sch_7.append(self.comboBox_7_9.currentText())
        sch_7.append(self.comboBox_7_10.currentText())
        sch_7.append(self.comboBox_7_11.currentText())
        sch_7.append(self.comboBox_7_12.currentText())
def create_schedule():        
    global sch_1,sch_2,sch_3,sch_4,sch_5,sch_6,sch_7
    try:
        schedule.every().monday.at(sch_1[0]).do(sch1)
        schedule.every().monday.at(sch_1[2]).do(sch2)
        schedule.every().monday.at(sch_1[4]).do(sch3)
        schedule.every().monday.at(sch_1[6]).do(sch4)
        schedule.every().monday.at(sch_1[8]).do(sch5)
        schedule.every().monday.at(sch_1[10]).do(sch6)
        
        schedule.every().tuesday.at(sch_2[0]).do(sch1)
        schedule.every().tuesday.at(sch_2[2]).do(sch2)
        schedule.every().tuesday.at(sch_2[4]).do(sch3)
        schedule.every().tuesday.at(sch_2[6]).do(sch4)
        schedule.every().tuesday.at(sch_2[8]).do(sch5)
        schedule.every().tuesday.at(sch_2[10]).do(sch6)

        schedule.every().wednesday.at(sch_3[0]).do(sch1)
        schedule.every().wednesday.at(sch_3[2]).do(sch2)
        schedule.every().wednesday.at(sch_3[4]).do(sch3)
        schedule.every().wednesday.at(sch_3[6]).do(sch4)
        schedule.every().wednesday.at(sch_3[8]).do(sch5)
        schedule.every().wednesday.at(sch_3[10]).do(sch6)

        schedule.every().thursday.at(sch_4[0]).do(sch1)
        schedule.every().thursday.at(sch_4[2]).do(sch2)
        schedule.every().thursday.at(sch_4[4]).do(sch3)
        schedule.every().thursday.at(sch_4[6]).do(sch4)
        schedule.every().thursday.at(sch_4[8]).do(sch5)
        schedule.every().thursday.at(sch_4[10]).do(sch6)

        schedule.every().friday.at(sch_5[0]).do(sch1)
        schedule.every().friday.at(sch_5[2]).do(sch2)
        schedule.every().friday.at(sch_5[4]).do(sch3)
        schedule.every().friday.at(sch_5[6]).do(sch4)
        schedule.every().friday.at(sch_5[8]).do(sch5)
        schedule.every().friday.at(sch_5[10]).do(sch6)
        
        schedule.every().saturday.at(sch_6[0]).do(sch1)
        schedule.every().saturday.at(sch_6[2]).do(sch2)
        schedule.every().saturday.at(sch_6[4]).do(sch3)
        schedule.every().saturday.at(sch_6[6]).do(sch4)
        schedule.every().saturday.at(sch_6[8]).do(sch5)
        schedule.every().saturday.at(sch_6[10]).do(sch6)

        schedule.every().sunday.at(sch_7[0]).do(sch1)
        schedule.every().sunday.at(sch_7[2]).do(sch2)
        schedule.every().sunday.at(sch_7[4]).do(sch3)
        schedule.every().sunday.at(sch_7[6]).do(sch4)
        schedule.every().sunday.at(sch_7[8]).do(sch5)
        schedule.every().sunday.at(sch_7[10]).do(sch6)
    except:
        pass
        
